version: '3.8'

services:

  db_postgres:
    image: ankane/pgvector:latest
    container_name: absensi_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: absensi_enterprise
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d absensi_enterprise"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis_cache:
    image: redis:alpine
    container_name: absensi_redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  ai_fastapi:
    build:
      context: ./ai-fastapi
      dockerfile: Dockerfile
    container_name: absensi_fastapi
    restart: unless-stopped
    ports:
      - "8001:8001"
    depends_on:
      db_postgres:
        condition: service_healthy

  laravel_app:
    build:
      context: ./backend-laravel
      dockerfile: Dockerfile
    container_name: absensi_laravel
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db_postgres
      DB_PORT: 5432
      DB_DATABASE: absensi_enterprise
      DB_USERNAME: admin
      DB_PASSWORD: secretpassword
      REDIS_HOST: redis_cache
      REDIS_PORT: 6379
      FASTAPI_URL: http://ai_fastapi:8001
    depends_on:
      db_postgres:
        condition: service_healthy
      redis_cache:
        condition: service_healthy

volumes:
  pgdata: